version: "3"

services:
  reverse-proxy:
    image: traefik
    command: --api.insecure=true --providers.docker
    restart: always
    ports: 
      - "80:80"
      - "8080:8080"
    volumes: 
      - ./traefik.toml:/Users/binbin.chen/Material/workspace/github/traefik-example/traefik.arthur.local.toml
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: traefik
    labels: 
      - "traefik.http.routers.api.rule=Host(`traefik.arthur.local`)"
      - "traefik.http.routers.api.service=api@internal"